[webserver]
port = ":8080"

[cache]
type="file"
basepath="cache"

#	OSM seamark objects
[[providers]]
name = "seamark"
type = "postgis"
host = ""
port = 5432
database = "osm_seamark"
user = ""
password = ""

	# Seamark Beacon Cardinal
	[[providers.layers]]
	name = "beacon_cardinal"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, colour FROM osm_beacon_cardinal WHERE geometry && !BBOX!"

	# Seamark Points
	[[providers.layers]]
	name = "points"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type FROM osm_seamarks WHERE geometry && !BBOX!"

	# Seamark Buoy Cardinal
	[[providers.layers]]
	name = "buoy_cardinal"
   	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type FROM osm_buoy_cardinal WHERE geometry && !BBOX!"


#	OSM land polygons and simplified land polygons
[[providers]]
name = "lp"
type = "postgis"
host = ""
port = 5432
database = "osm_land_polygons"
user = ""
password = ""

	# Land
	[[providers.layers]]
	name = "land_0-9"
	geometry_fieldname = "geometry"
	id_fieldname = "fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid FROM simplified_land_polygons WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "land_10-20"
	geometry_fieldname = "geometry"
	id_fieldname = "fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid FROM land_polygons WHERE wkb_geometry && !BBOX!"

#	Open Street Maps (OSM)
[[providers]]
name = "osm"
type = "postgis"
host = ""
port = 5432
database = "italy_2018_01_25"
user = "tegola"
password = ""
max_connections = 500

	# Water
	[[providers.layers]]
	name = "water_areas"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, area, tags FROM osm_water_areas WHERE type IN ('water', 'pond', 'basin', 'canal', 'mill_pond', 'riverbank', 'dock') AND geometry && !BBOX!"

	[[providers.layers]]
	name = "water_areas_gen0"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, area, tags FROM osm_water_areas_gen0 WHERE type IN ('water', 'pond', 'basin', 'canal', 'mill_pond', 'riverbank') AND area > 10000 AND geometry && !BBOX!"

	[[providers.layers]]
	name = "water_areas_gen1"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, area, tags FROM osm_water_areas_gen1 WHERE type IN ('water', 'pond', 'basin', 'canal', 'mill_pond', 'riverbank') AND area > 1000 AND geometry && !BBOX!"

	[[providers.layers]]
	name = "water_lines"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, tags FROM osm_water_lines WHERE type IN ('river', 'canal', 'stream', 'ditch', 'drain', 'dam') AND geometry && !BBOX!"

	[[providers.layers]]
	name = "water_lines_gen0"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, tags FROM osm_water_lines WHERE type IN ('river', 'canal') AND geometry && !BBOX!"

	[[providers.layers]]
	name = "water_lines_gen1"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, tags FROM osm_water_lines WHERE type IN ('river', 'canal', 'stream', 'ditch', 'drain', 'dam') AND geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_boundaries_11-12"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, admin_level, tags FROM osm_admin_areas WHERE admin_level IN (1,2,3,4,5,6,7,8) AND geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_boundaries_13-20"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, admin_level, tags FROM osm_admin_areas WHERE admin_level IN (1,2,3,4,5,6,7,8,9,10) AND geometry && !BBOX!"

	# Land Use
	[[providers.layers]]
	name = "landuse_areas"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, class, type, area, tags FROM osm_landuse_areas WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "landuse_areas_gen0"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, class, type, area, tags FROM osm_landuse_areas_gen0 WHERE type IN ('forest','wood','nature reserve', 'military') AND geometry && !BBOX!"

	[[providers.layers]]
	name = "landuse_areas_gen1"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, class, type, area, tags FROM osm_landuse_areas_gen1 WHERE geometry && !BBOX!"

	# Transport
	[[providers.layers]]
	name = "transport_points"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, class, tags, type FROM osm_transport_points WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "transport_areas"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, class, type, tags FROM osm_transport_areas WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "transport_lines_gen1"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, ref, class, type, tags, tunnel, bridge FROM osm_transport_lines_gen1 WHERE type IN ('motorway', 'trunk', 'primary', 'primary_link', 'secondary', 'motorway_link', 'trunk_link') AND geometry && !BBOX!"

	[[providers.layers]]
	name = "transport_lines_gen0"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, ref, class, type, tags, tunnel, bridge FROM osm_transport_lines_gen0 WHERE type IN ('motorway','trunk') AND  geometry && !BBOX!"

	[[providers.layers]]
	name = "transport_lines_11-12"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, ref, class, type, tags, tunnel, bridge, access, service FROM osm_transport_lines WHERE type IN ('motorway', 'motorway_link', 'trunk', 'trunk_link', 'primary', 'primary_link', 'secondary', 'secondary_link', 'tertiary', 'tertiary_link', 'rail', 'taxiway', 'runway', 'apron') AND geometry && !BBOX!"

	[[providers.layers]]
	name = "transport_lines_13"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, ref, class, type, tags, tunnel, bridge, access, service FROM osm_transport_lines WHERE type IN ('motorway', 'motorway_link', 'trunk', 'trunk_link', 'primary', 'primary_link', 'secondary', 'secondary_link', 'tertiary', 'tertiary_link', 'rail', 'residential', 'taxiway', 'runway', 'apron') AND geometry && !BBOX!"

	[[providers.layers]]
	name = "transport_lines_14-20"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, ref, class, type, tags, tunnel, bridge, access, service FROM osm_transport_lines WHERE geometry && !BBOX!"

	# Amenities
	[[providers.layers]]
	name = "amenity_areas"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, tags FROM osm_amenity_areas WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "amenity_points"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, tags FROM osm_amenity_points WHERE geometry && !BBOX!"

	# Other (Man Made, Historic, Military, Power, Barrier etc)
	[[providers.layers]]
	name = "other_points"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, class, type, tags FROM osm_other_points WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "other_lines"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, class, type, tags FROM osm_other_lines WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "other_areas"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, class, type, tags FROM osm_other_areas WHERE geometry && !BBOX!"

	# Buildings
	[[providers.layers]]
	name = "buildings"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, height, type, tags FROM osm_buildings WHERE geometry && !BBOX!"

#	Natural Earth
[[providers]]
name = "ne"
type = "postgis"
host = ""
port = 5432
database = "natural_earth"
user = ""
password = ""

	[[providers.layers]]
	name = "admin_boundaries_0-2"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, featurecla, name, name_alt FROM ne_110m_admin_0_boundary_lines_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_countries_5-6"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, labelrank, name FROM ne_10m_admin_0_countries WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_boundaries_3-4"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, featurecla, name FROM ne_50m_admin_0_boundary_lines_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_boundaries_disputed_3-4"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, featurecla, name FROM ne_50m_admin_0_boundary_lines_disputed_areas WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_states_provinces_lines_3-4"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, name FROM ne_50m_admin_1_states_provinces_lines WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_boundaries_5-6"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, featurecla, name FROM ne_10m_admin_0_boundary_lines_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_boundaries_disputed_5-6"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, featurecla, name FROM ne_10m_admin_0_boundary_lines_disputed_areas WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_states_provinces_lines_5-6"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, name FROM ne_10m_admin_1_states_provinces_lines WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_label_points_3-20"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, name FROM ne_50m_admin_1_states_provinces_lines WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "admin_label_points_5-20"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, name, adm0_sr, datarank FROM ne_10m_admin_1_label_points WHERE wkb_geometry && !BBOX!"

[[maps]]
name = "osm"
attribution = "Open Street Map" # map attribution
center = [12.4491840123102, 41.708155941304, 6.0] # optional center value. part of the TileJSON spec

	# Country Lines
	[[maps.layers]]
	name = "admin_boundaries_0-2"
	provider_layer = "ne.admin_boundaries_0-2"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "admin_boundaries_3-4"
	provider_layer = "ne.admin_boundaries_3-4"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "admin_boundaries_5-6"
	provider_layer = "ne.admin_boundaries_5-6"
	min_zoom = 5
	max_zoom = 10

	[[maps.layers]]
	name = "admin_boundaries_disputed_3-4"
	provider_layer = "ne.admin_boundaries_disputed_3-4"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "admin_boundaries_disputed_5-6"
	provider_layer = "ne.admin_boundaries_disputed_5-6"
	min_zoom = 5
	max_zoom = 6

	[[maps.layers]]
	name = "admin_label_points_3-20"
	provider_layer = "ne.admin_label_points_3-20"
	min_zoom = 3
	max_zoom = 20

	# Country Polygons
	[[maps.layers]]
	name = "country_polygons"
	provider_layer = "ne.admin_countries_5-6"
	min_zoom = 5
	max_zoom = 10

	[[maps.layers]]
	name = "admin_boundaries_11-12"
	provider_layer = "osm.admin_boundaries_11-12"
	min_zoom = 11
	max_zoom = 12

	[[maps.layers]]
	name = "admin_boundaries_13-20"
	provider_layer = "osm.admin_boundaries_13-20"
	min_zoom = 13
	max_zoom = 20

	[[maps.layers]]
	name = "admin_label_points_5-20"
	provider_layer = "ne.admin_label_points_5-20"
	min_zoom = 5
	max_zoom = 20

	# State Polygons
	[[maps.layers]]
	name = "admin_states_provinces_lines_3-4"
	provider_layer = "ne.admin_states_provinces_lines_3-4"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "admin_states_provinces_lines_5-20"
	provider_layer = "ne.admin_states_provinces_lines_5-6"
	min_zoom = 5
	max_zoom = 20

	# Land
	[[maps.layers]]
	name = "land_0-9"
	provider_layer = "lp.land_0-9"
	min_zoom = 0
	max_zoom = 9

	[[maps.layers]]
	name = "land_10-20"
	provider_layer = "lp.land_10-20"
	min_zoom = 10
	max_zoom = 20

	# Land Use
	[[maps.layers]]
	name = "landusages_gen0"
	provider_layer = "osm.landuse_areas_gen0"
	min_zoom = 3
	max_zoom = 9

	[[maps.layers]]
	name = "landusages_gen1"
	provider_layer = "osm.landuse_areas_gen1"
	min_zoom = 10
	max_zoom = 12

	[[maps.layers]]
	name = "landusages"
	provider_layer = "osm.landuse_areas"
	min_zoom = 13
	max_zoom = 20

	# Water Areas
	[[maps.layers]]
	name = "waterareas_gen0"
	provider_layer = "osm.water_areas_gen0"
	min_zoom = 3
	max_zoom = 9

	[[maps.layers]]
	name = "waterareas_gen1"
	provider_layer = "osm.water_areas_gen1"
	min_zoom = 10
	max_zoom = 12

	[[maps.layers]]
	name = "waterareas"
	provider_layer = "osm.water_areas"
	min_zoom = 13
	max_zoom = 20

	# Water Lines
	[[maps.layers]]
	name = "waterways_gen0"
	provider_layer = "osm.water_lines_gen0"
	min_zoom = 8
	max_zoom = 12

	[[maps.layers]]
	name = "waterways_gen1"
	provider_layer = "osm.water_lines_gen1"
	min_zoom = 13
	max_zoom = 14

	[[maps.layers]]
	name = "waterways"
	provider_layer = "osm.water_lines"
	min_zoom = 15
	max_zoom = 20

	# Transport Lines (Roads, Rail, Aviation)
	[[maps.layers]]
	name = "roads_gen0"
	provider_layer = "osm.transport_lines_gen0"
	min_zoom = 4
	max_zoom = 8

	[[maps.layers]]
	name = "roads_gen1"
	provider_layer = "osm.transport_lines_gen1"
	min_zoom = 9
	max_zoom = 10

	[[maps.layers]]
	name = "roads_11-12"
	provider_layer = "osm.transport_lines_11-12"
	min_zoom = 11
	max_zoom = 12

	[[maps.layers]]
	name = "roads_13"
	provider_layer = "osm.transport_lines_13"
	min_zoom = 13
	max_zoom = 13

	[[maps.layers]]
	name = "roads_14-20"
	provider_layer = "osm.transport_lines_14-20"
	min_zoom = 14
	max_zoom = 20

	# Transport Areas
	[[maps.layers]]
	name = "transport_areas"
	provider_layer = "osm.transport_areas"
	min_zoom = 12
	max_zoom = 20

	# Transport Points
	[[maps.layers]]
	name = "transport_points"
	provider_layer = "osm.transport_points"
	min_zoom = 14
	max_zoom = 20

	# Amenity Areas
	[[maps.layers]]
	name = "amenity_areas"
	provider_layer = "osm.amenity_areas"
	min_zoom = 14
	max_zoom = 20

	# Amenity Points
	[[maps.layers]]
	name = "amenity_points"
	provider_layer = "osm.amenity_points"
	min_zoom = 14
	max_zoom = 20

	# Other Points
	[[maps.layers]]
	name = "other_points"
	provider_layer = "osm.other_points"
	min_zoom = 14
	max_zoom = 20

	# Other Lines
	[[maps.layers]]
	name = "other_lines"
	provider_layer = "osm.other_lines"
	min_zoom = 14
	max_zoom = 20

	# Other Areas
	[[maps.layers]]
	name = "other_areas"
	provider_layer = "osm.other_areas"
	min_zoom = 6
	max_zoom = 20

	# Buildings
	[[maps.layers]]
	name = "buildings"
	provider_layer = "osm.buildings"
	min_zoom = 14
	max_zoom = 20

	# Seamark Objects
	[[maps.layers]]
	name = "seamark_beacon_cardinal"
	provider_layer = "seamark.beacon_cardinal"
	min_zoom = 2
	max_zoom = 20

	[[maps.layers]]
	name = "seamark_points"
	provider_layer = "seamark.points"
	min_zoom = 2
	max_zoom = 20

	[[maps.layers]]
	name = "seamark_buoy_cardinal"
	provider_layer = "seamark.buoy_cardinal"
	min_zoom = 2
	max_zoom = 20